# gcloud builds submit --project arctiqteam-images --timeout=3600s --substitutions=TAG_NAME="v1.0.0"
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/microservices-demo/adservice:$TAG_NAME'
    - './src/adservice'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/microservices-demo/cartservice:$TAG_NAME'
    - './src/cartservice'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/microservices-demo/checkoutservice:$TAG_NAME'
    - './src/checkoutservice'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/microservices-demo/currencyservice:$TAG_NAME'
    - './src/currencyservice'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/microservices-demo/emailservice:$TAG_NAME'
    - './src/emailservice'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/microservices-demo/frontend:$TAG_NAME'
    - './src/frontend'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/microservices-demo/loadgenerator:$TAG_NAME'
    - './src/loadgenerator'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/microservices-demo/paymentservice:$TAG_NAME'
    - './src/paymentservice'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/microservices-demo/productcatalogservice:$TAG_NAME'
    - './src/productcatalogservice'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/microservices-demo/recommendationservice:$TAG_NAME'
    - './src/recommendationservice'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/microservices-demo/shippingservice:$TAG_NAME'
    - './src/shippingservice'
images:
  - gcr.io/$PROJECT_ID/microservices-demo/adservice:$TAG_NAME
  - gcr.io/$PROJECT_ID/microservices-demo/cartservice:$TAG_NAME
  - gcr.io/$PROJECT_ID/microservices-demo/checkoutservice:$TAG_NAME
  - gcr.io/$PROJECT_ID/microservices-demo/currencyservice:$TAG_NAME
  - gcr.io/$PROJECT_ID/microservices-demo/emailservice:$TAG_NAME
  - gcr.io/$PROJECT_ID/microservices-demo/frontend:$TAG_NAME
  - gcr.io/$PROJECT_ID/microservices-demo/loadgenerator:$TAG_NAME
  - gcr.io/$PROJECT_ID/microservices-demo/paymentservice:$TAG_NAME
  - gcr.io/$PROJECT_ID/microservices-demo/productcatalogservice:$TAG_NAME
  - gcr.io/$PROJECT_ID/microservices-demo/recommendationservice:$TAG_NAME
  - gcr.io/$PROJECT_ID/microservices-demo/shippingservice:$TAG_NAME
