# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This configuration file is used to build and deploy the app into a 
# GKE cluster using Google Cloud Build.
#
# PREREQUISITES:
# - Cloud Build service account must have role: "Kubernetes Engine Developer"

# USAGE:
# GCP zone and GKE target cluster must be specified as substitutions
# Example invocation:
# `gcloud builds submit --config=cloudbuild.yaml --substitutions=_ZONE=us-central1-b,_CLUSTER=demo-app-staging .`

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/microservices-demo/adservice:$TAG_NAME'
    - './src/adservice'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/microservices-demo/cartservice:$TAG_NAME'
    - './src/cartservice'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/microservices-demo/checkoutservice:$TAG_NAME'
    - './src/checkoutservice'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/microservices-demo/currencyservice:$TAG_NAME'
    - './src/currencyservice'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/microservices-demo/emailservice:$TAG_NAME'
    - './src/emailservice'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/microservices-demo/frontend:$TAG_NAME'
    - './src/frontend'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/microservices-demo/loadgenerator:$TAG_NAME'
    - './src/loadgenerator'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/microservices-demo/paymentservice:$TAG_NAME'
    - './src/paymentservice'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/microservices-demo/productcatalogservice:$TAG_NAME'
    - './src/productcatalogservice'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/microservices-demo/recommendationservice:$TAG_NAME'
    - './src/recommendationservice'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/microservices-demo/shippingservice:$TAG_NAME'
    - './src/shippingservice'
images:
  - gcr.io/$PROJECT_ID/microservices-demo/adservice:$TAG_NAME
  - gcr.io/$PROJECT_ID/microservices-demo/cartservice:$TAG_NAME
  - gcr.io/$PROJECT_ID/microservices-demo/checkoutservice:$TAG_NAME
  - gcr.io/$PROJECT_ID/microservices-demo/currencyservice:$TAG_NAME
  - gcr.io/$PROJECT_ID/microservices-demo/emailservice:$TAG_NAME
  - gcr.io/$PROJECT_ID/microservices-demo/frontend:$TAG_NAME
  - gcr.io/$PROJECT_ID/microservices-demo/loadgenerator:$TAG_NAME
  - gcr.io/$PROJECT_ID/microservices-demo/paymentservice:$TAG_NAME
  - gcr.io/$PROJECT_ID/microservices-demo/productcatalogservice:$TAG_NAME
  - gcr.io/$PROJECT_ID/microservices-demo/recommendationservice:$TAG_NAME
  - gcr.io/$PROJECT_ID/microservices-demo/shippingservice:$TAG_NAME
